name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y wget unzip libqt6printsupport6

      - name: Install MiniZinc
        run: |
          MINIZINC_VERSION=2.8.5
          wget -q https://github.com/MiniZinc/MiniZincIDE/releases/download/${MINIZINC_VERSION}/MiniZincIDE-${MINIZINC_VERSION}-x86_64.AppImage
          chmod +x MiniZincIDE-${MINIZINC_VERSION}-x86_64.AppImage
          ./MiniZincIDE-${MINIZINC_VERSION}-x86_64.AppImage --appimage-extract >/dev/null
          sudo mv squashfs-root /opt/minizinc
          sudo ln -sf /opt/minizinc/usr/bin/minizinc /usr/local/bin/minizinc

      - name: Configure MiniZinc environment
        run: |
          echo "MINIZINC_DIR=/opt/minizinc/usr/share/minizinc" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=/opt/minizinc/usr/lib" >> $GITHUB_ENV
          echo "/opt/minizinc/usr/bin" >> $GITHUB_PATH

      - name: Verify MiniZinc
        run: minizinc --version

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest pytest-asyncio pytest-timeout

      - name: Run tests
        run: pytest -q

